---
- name: Construir y subir imagen al ACR usando Docker
  hosts: localhost
  vars:
    acr_name: "exampleacr3"  # Nombre de tu ACR
    acr_url: "exampleacr3.azurecr.io"  # Servidor de login de tu ACR
    acr_username: "exampleacr3"  # Usuario del ACR 
    acr_password: ""  # Contraseña del ACR 
  tasks:
    - name: Autenticar en el ACR
      command: >
        docker login {{ acr_url }} -u {{ acr_username }} -p {{ acr_password }}

    - name: Construir imagen Docker
      command: >
        docker build -t {{ acr_url }}/casopractico2 .

    - name: Subir imagen al ACR
      command: >
        docker push {{ acr_url }}/casopractico2